[package]
name = "physdes-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "physdes"
path = "src/lib.rs"

[dependencies]
num = { version = "0.4.0" }
num-traits = { version = "0.2.14" }
intervallum = { version = "1.3.0" }
# lds-rs = { path = "lds-rs" }
