//! SVG visualizer for clock trees generated by the DME algorithm.
//!
//! Provides `ClockTreeVisualizer` for rendering clock trees as scalable SVG
//! graphics with node coloring (root/internal/sink), wire length labels,
//! delay and capacitance annotations, and an optional analysis info panel.

use std::cell::RefCell;
use std::rc::Rc;

use crate::dme_algorithm::{SkewAnalysis, TreeNode};

/// SVG visualizer for DME clock trees.
///
/// Color-codes nodes by type (root=red, internal=blue, sinks=green),
/// draws parent-child wires with length labels, and overlays delay/capacitance
/// info. Optionally displays a skew analysis panel.
pub struct ClockTreeVisualizer {
    pub margin: u32,
    pub node_radius: u32,
    pub wire_width: u32,
    pub sink_color: String,
    pub internal_color: String,
    pub root_color: String,
    pub wire_color: String,
    pub text_color: String,
}

impl Default for ClockTreeVisualizer {
    fn default() -> Self {
        Self {
            margin: 50,
            node_radius: 8,
            wire_width: 2,
            sink_color: "#4CAF50".into(),
            internal_color: "#2196F3".into(),
            root_color: "#F44336".into(),
            wire_color: "#666666".into(),
            text_color: "#333333".into(),
        }
    }
}

impl ClockTreeVisualizer {
    pub fn new() -> Self {
        Self::default()
    }

    /// Produce an SVG string visualizing the clock tree rooted at `root`.
    ///
    /// * `root` — root of the clock tree (from `DMEAlgorithm::build_clock_tree`)
    /// * `sinks` — original sink list (used to identify leaf nodes)
    /// * `filename` — if non-empty, save the SVG to this path
    /// * `width`, `height` — SVG canvas dimensions
    /// * `analysis` — optional `SkewAnalysis` to display in an info panel
    pub fn visualize_tree(
        &self,
        root: Rc<RefCell<TreeNode>>,
        sinks: &[crate::dme_algorithm::Sink],
        filename: &str,
        width: u32,
        height: u32,
        analysis: Option<&SkewAnalysis>,
    ) -> String {
        let all_nodes = collect_all_nodes(&root);
        let (min_x, min_y, max_x, max_y) = calculate_bounds(&all_nodes, sinks);

        let range_x = (max_x - min_x).max(1) as f64;
        let range_y = (max_y - min_y).max(1) as f64;
        let m = self.margin as f64;
        let sx = (width as f64 - 2.0 * m) / range_x;
        let sy = (height as f64 - 2.0 * m) / range_y;
        let scale = sx.min(sy);

        let sc = |x: i32, y: i32| -> (f64, f64) {
            (
                m + (x as f64 - min_x as f64) * scale,
                m + (y as f64 - min_y as f64) * scale,
            )
        };

        let mut svg = String::new();
        svg.push_str(&format!(
            r#"<svg width="{}" height="{}" xmlns="http://www.w3.org/2000/svg">"#,
            width, height
        ));
        svg.push_str(&format!(
            r#"<style>.nl{{font:{}px sans-serif;fill:{}}}.dl{{font:{}px sans-serif;fill:{}}}</style>"#,
            10, self.text_color, 8, self.text_color
        ));
        svg.push_str(r#"<rect width="100%" height="100%" fill="white"/>"#);

        // Wires
        svg.push_str(&draw_wires(&root, &sc, &self.wire_color, self.wire_width));

        // Nodes
        svg.push_str(&draw_nodes(
            &root,
            sinks,
            &sc,
            self.root_color.as_str(),
            self.internal_color.as_str(),
            self.sink_color.as_str(),
            self.node_radius,
        ));

        // Analysis panel
        if let Some(a) = analysis {
            svg.push_str(&create_analysis_box(a));
        }

        svg.push_str("</svg>");

        if !filename.is_empty() {
            let _ = std::fs::write(filename, &svg);
            eprintln!("Clock tree SVG saved to {}", filename);
        }
        svg
    }
}

// --- helper helpers (non-allocating DFS helpers) ---

fn collect_all_nodes(root: &Rc<RefCell<TreeNode>>) -> Vec<Rc<RefCell<TreeNode>>> {
    let mut nodes = Vec::new();
    let mut stack = vec![Rc::clone(root)];
    while let Some(node) = stack.pop() {
        nodes.push(Rc::clone(&node));
        let n = node.borrow();
        if let Some(ref r) = n.right {
            stack.push(Rc::clone(r));
        }
        if let Some(ref l) = n.left {
            stack.push(Rc::clone(l));
        }
    }
    nodes
}

fn calculate_bounds(
    nodes: &[Rc<RefCell<TreeNode>>],
    sinks: &[crate::dme_algorithm::Sink],
) -> (i32, i32, i32, i32) {
    let mut min_x = i32::MAX;
    let mut min_y = i32::MAX;
    let mut max_x = i32::MIN;
    let mut max_y = i32::MIN;

    for node in nodes {
        let n = node.borrow();
        min_x = min_x.min(n.position.xcoord);
        min_y = min_y.min(n.position.ycoord);
        max_x = max_x.max(n.position.xcoord);
        max_y = max_y.max(n.position.ycoord);
    }
    for sink in sinks {
        min_x = min_x.min(sink.position.xcoord);
        min_y = min_y.min(sink.position.ycoord);
        max_x = max_x.max(sink.position.xcoord);
        max_y = max_y.max(sink.position.ycoord);
    }

    if min_x == i32::MAX {
        return (0, 0, 100, 100);
    }

    let padding = ((max_x - min_x).max(max_y - min_y) as f64 * 0.1).max(10.0) as i32;
    (
        min_x - padding,
        min_y - padding,
        max_x + padding,
        max_y + padding,
    )
}

fn sink_positions(sinks: &[crate::dme_algorithm::Sink]) -> Vec<(i32, i32)> {
    sinks.iter().map(|s| (s.position.xcoord, s.position.ycoord)).collect()
}

fn draw_wires(
    root: &Rc<RefCell<TreeNode>>,
    sc: &dyn Fn(i32, i32) -> (f64, f64),
    color: &str,
    width: u32,
) -> String {
    let mut out = String::new();
    let mut stack = vec![(Rc::clone(root), false)];
    while let Some((node, _)) = stack.pop() {
        let n = node.borrow();
        if let Some(ref parent) = n.parent {
            let pb = parent.borrow();
            let (x1, y1) = sc(pb.position.xcoord, pb.position.ycoord);
            let (x2, y2) = sc(n.position.xcoord, n.position.ycoord);
            out.push_str(&format!(
                r#"<line x1="{}" y1="{}" x2="{}" y2="{}" stroke="{}" stroke-width="{}" stroke-linecap="round"/>"#,
                x1, y1, x2, y2, color, width
            ));
            if n.wire_length > 0 {
                let mx = (x1 + x2) / 2.0;
                let my = (y1 + y2) / 2.0;
                out.push_str(&format!(
                    r#"<text x="{}" y="{}" class="dl" text-anchor="middle">{}</text>"#,
                    mx, my - 5.0, n.wire_length
                ));
            }
        }
        if let Some(ref r) = n.right {
            stack.push((Rc::clone(r), false));
        }
        if let Some(ref l) = n.left {
            stack.push((Rc::clone(l), false));
        }
    }
    out
}

fn draw_nodes(
    root: &Rc<RefCell<TreeNode>>,
    sinks: &[crate::dme_algorithm::Sink],
    sc: &dyn Fn(i32, i32) -> (f64, f64),
    root_color: &str,
    internal_color: &str,
    sink_color: &str,
    radius: u32,
) -> String {
    let sink_set: std::collections::HashSet<(i32, i32)> =
        sink_positions(sinks).into_iter().collect();
    let mut out = String::new();
    let mut stack = vec![(Rc::clone(root), 0u32)];
    while let Some((node, depth)) = stack.pop() {
        let n = node.borrow();
        let (x, y) = sc(n.position.xcoord, n.position.ycoord);
        let is_root = n.parent.is_none();
        let is_sink = sink_set.contains(&(n.position.xcoord, n.position.ycoord));

        let (color, r) = if is_root {
            (root_color, radius + 2)
        } else if is_sink {
            (sink_color, radius)
        } else {
            (internal_color, radius - 2)
        };

        let r = r as f64;
        out.push_str(&format!(
            "<circle cx=\"{}\" cy=\"{}\" r=\"{}\" fill=\"{}\" stroke=\"{}333\" stroke-width=\"1\"/>",
            x, y, r, color, '#'
        ));
        // Name label
        out.push_str(&format!(
            r#"<text x="{}" y="{}" class="nl" text-anchor="middle">{}</text>"#,
            x,
            y - r - 5.0,
            n.name
        ));
        // Delay
        out.push_str(&format!(
            r#"<text x="{}" y="{}" class="dl" text-anchor="middle">d:{:.1}</text>"#,
            x,
            y + r + 12.0,
            n.delay
        ));
        // Capacitance for sinks
        if is_sink {
            out.push_str(&format!(
                r#"<text x="{}" y="{}" class="dl" text-anchor="middle">c:{:.1}</text>"#,
                x,
                y + r + 22.0,
                n.capacitance
            ));
        }

        let right = n.right.as_ref().map(Rc::clone);
        let left = n.left.as_ref().map(Rc::clone);
        drop(n);
        if let Some(rn) = right {
            stack.push((rn, depth + 1));
        }
        if let Some(ln) = left {
            stack.push((ln, depth + 1));
        }
    }
    out
}

fn create_analysis_box(analysis: &SkewAnalysis) -> String {
    let mut s = String::new();
    s.push_str(r#"<g class="analysis-info">"#);
    s.push_str(&format!(
        "<rect x=\"10\" y=\"10\" width=\"220\" height=\"140\" fill=\"white\" stroke=\"{}ccc\" stroke-width=\"1\" rx=\"5\"/>",
        '#'
    ));
    s.push_str(&format!(
        "<rect x=\"10\" y=\"10\" width=\"220\" height=\"20\" fill=\"#f0f0f0\" stroke=\"{}ccc\" stroke-width=\"1\" rx=\"5\"/>",
        '#'
    ));
    s.push_str(&format!(
        "<text x=\"20\" y=\"25\" font-family=\"sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"{}333\">Clock Tree Analysis</text>",
        '#'
    ));
    s.push_str(&format!(
        "<text x=\"20\" y=\"45\" font-family=\"monospace\" font-size=\"11\" fill=\"{}333\">",
        '#'
    ));

    let lines = [
        format!("Delay Model: {}", analysis.delay_model),
        format!("Max Delay: {:.3}", analysis.max_delay),
        format!("Min Delay: {:.3}", analysis.min_delay),
        format!("Skew: {:.3}", analysis.skew),
        format!("Total WL: {}", analysis.total_wirelength),
        format!("Sinks: {}", analysis.sink_delays.len()),
    ];
    for (i, line) in lines.iter().enumerate() {
        s.push_str(&format!(
            r#"<tspan x="20" y="{}">{}</tspan>"#,
            45 + (i as u32 + 1) * 16,
            line
        ));
    }

    s.push_str("</text></g>");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dme_algorithm::*;
    use crate::Point;

    fn sample_sinks() -> Vec<Sink> {
        vec![
            Sink::new("s1", Point::new(0, 0), 1.0),
            Sink::new("s2", Point::new(10, 0), 1.0),
            Sink::new("s3", Point::new(10, 10), 1.0),
            Sink::new("s4", Point::new(0, 10), 1.0),
        ]
    }

    fn build_test_tree(sinks: Vec<Sink>) -> (DMEAlgorithm, Rc<RefCell<TreeNode>>) {
        let calc = Box::new(LinearDelayCalculator::new(0.5, 0.1));
        let mut dme = DMEAlgorithm::new(sinks, calc);
        let root = dme.build_clock_tree();
        (dme, root)
    }

    #[test]
    fn test_visualizer_produces_valid_svg() {
        let sinks = sample_sinks();
        let (dme, root) = build_test_tree(sinks.clone());
        let analysis = dme.analyze_skew(Rc::clone(&root));
        let viz = ClockTreeVisualizer::new();
        let svg = viz.visualize_tree(root, &sinks, "", 400, 300, Some(&analysis));

        assert!(svg.starts_with("<svg"));
        assert!(svg.ends_with("</svg>"));
        assert!(svg.contains("Clock Tree Analysis"));
        assert!(svg.contains("Max Delay"));
        assert!(svg.contains("d:"));
    }

    #[test]
    fn test_visualizer_svg_contains_all_nodes() {
        let sinks = sample_sinks();
        let (dme, root) = build_test_tree(sinks.clone());
        let analysis = dme.analyze_skew(Rc::clone(&root));
        let viz = ClockTreeVisualizer::new();
        let svg = viz.visualize_tree(root, &sinks, "", 400, 300, Some(&analysis));

        // All sink names should appear in the SVG
        for sink in &sinks {
            assert!(svg.contains(&sink.name), "Missing node: {}", sink.name);
        }
    }

    #[test]
    fn test_visualizer_skew_within_two_percent() {
        let sinks = sample_sinks();
        let (dme, root) = build_test_tree(sinks.clone());
        let analysis = dme.analyze_skew(Rc::clone(&root));

        assert!(analysis.max_delay > 0.0);
        let pct = analysis.skew / analysis.max_delay * 100.0;
        assert!(
            pct < 2.0,
            "Skew {:.4} ({:.2}%) exceeds 2%",
            analysis.skew,
            pct
        );
    }

    #[test]
    fn test_visualizer_generates_svg_file() {
        let sinks = sample_sinks();
        let (dme, root) = build_test_tree(sinks.clone());
        let analysis = dme.analyze_skew(Rc::clone(&root));
        let viz = ClockTreeVisualizer::new();
        let path = "test_clock_tree.svg";
        let svg = viz.visualize_tree(root, &sinks, path, 800, 600, Some(&analysis));

        assert!(std::path::Path::new(path).exists());
        let saved = std::fs::read_to_string(path).unwrap();
        assert_eq!(saved, svg);
        let _ = std::fs::remove_file(path);
    }
}
